apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  labels:
    name: nomad
spec:
  type: {{ .Values.svc.type }}
  ports:
    {{- range .Values.svc.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
    {{- end}}
  selector:
    app: nomad